version: '3.3'

services:
  base: &base
    image: hooopo/tipanel:latest
    env_file: .env.production

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env.production
    volumes:
      - redis:/data/redis
    ports:
      - '6380:6379'

  openresty:
    tty: true
    restart: always
    stdin_open: true
    ports:
      - '8000:8000'
    image: hooopo/tipanel-openresty:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  geoipupdate:
    container_name: geoipupdate
    image: maxmindinc/geoipupdate
    restart: unless-stopped
    env_file: .env.production
    environment:
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country'
      - GEOIPUPDATE_FREQUENCY=72
    volumes:
      - 'geoipupdate_data:/usr/share/GeoIP/'

  rails:
    <<: *base
    image: hooopo/tipanel:latest
    dns:
      - 8.8.8.8
    restart: always
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    depends_on:
      - redis
      - sidekiq
    ports:
      - 3333:3000
    env_file: .env.production
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  sidekiq:
    <<: *base
    image: hooopo/tipanel:latest
    dns:
      - 8.8.8.8
    restart: always
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - 'geoipupdate_data:/usr/share/GeoIP/'
    depends_on:
      - redis
      - geoipupdate
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

volumes:
  redis:
  packs:
  node_modules:
  cache:
  bundle:
  geoipupdate_data:
    driver: local
