default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  adapter: tidb
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: 127.0.0.1
  port: 4000
  variables:
    tidb_enable_noop_functions: ON
  username: root
  password:

development:
  <<: *default
  database: tipanel_test
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: tipanel_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: tipanel
  pool: 25
  url: <%= ENV['DATABASE_URL'] %>