# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: true
:concurrency: 10
:timeout: 25

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - event1
  - event2
  - event3
  - event4
  - event5
  - event6
  - event7
  - event8
  - event9
  - event10
  - critical
  - default
  - low

# you can override concurrency based on environment
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 25 %>
staging:
  :concurrency: 15
